# Generated by Django 5.1.6 on 2025-02-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='ai_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
